// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_PSXSGcCligPzv4q3xmnptNDyYj6N08',
    appId: '1:86566537778:web:d24b278e8e78a630fc8a2b',
    messagingSenderId: '86566537778',
    projectId: 'e-commerce-d6c8a',
    authDomain: 'e-commerce-d6c8a.firebaseapp.com',
    databaseURL: 'https://e-commerce-d6c8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-d6c8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEL0FfHkzHxc14EPXr45s_Eijx8gwMCts',
    appId: '1:86566537778:android:e529c4b52d19bde7fc8a2b',
    messagingSenderId: '86566537778',
    projectId: 'e-commerce-d6c8a',
    databaseURL: 'https://e-commerce-d6c8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-d6c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOurPBHJo5JiaoOmGr2Id2Pvnnny79boM',
    appId: '1:86566537778:ios:8c03412be2e8abc5fc8a2b',
    messagingSenderId: '86566537778',
    projectId: 'e-commerce-d6c8a',
    databaseURL: 'https://e-commerce-d6c8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-d6c8a.appspot.com',
    iosBundleId: 'com.example.assignment',
  );
}
